jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:   # minimal permissions since we only call external webhook
      contents: read
    steps:
      - name: Send PR info to Discord
        if: ${{ secrets.DISCORD_OPENED_PR_WEBHOOK_URL != '' }}
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_OPENED_PR_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"content\": \"📢 New Pull Request Created!\n**#${PR_NUMBER}**: ${PR_TITLE}\n🧑‍💻 Author: ${PR_USER}\n🔗 ${PR_URL}\"
            }" \
            $DISCORD_WEBHOOK
            