name: CookingLab PR Bot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  issues: write
  pull-requests: write

jobs:
  review_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install dependencies (Node.js)
        run: |
          npm install -g eslint
          npm install
          
      - name: Run ESLint (TypeScript)
        id: lint_ts
        continue-on-error: true
        run: |
          npx eslint --max-warnings=0 --quiet '**/*.ts' '**/*.tsx'

      - name: Install dependencies (Python)
        run: |
          python -m pip install --upgrade pip
          pip install flake8 radon requests

      - name: Run PR Review Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python .github/scripts/review_pr.py

      - name: Send Lint Result to Discord
        if: always()  # ensure this step runs even if previous one fails
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ "${{ steps.lint_ts.outcome }}" = "success" ]; then
            STATUS="✅ Linting passed!"
          else
            STATUS="❌ Linting failed."
          fi

          MESSAGE="**Lint Check Result for PR #${{ github.event.pull_request.number }}**\n$STATUS\n🔗 [View PR](${{ github.event.pull_request.html_url }})"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               $DISCORD_OPENED_PR_WEBHOOK_URL
